# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XGn5CkSv_XSlHTjQdlkbn82xFJJNSoZ1

Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:


*   R
*   Python
*   Ruby

Some of the commonly used libraries used by Data Scientists include:


*   Pandas
*   Numpy


*   Scikit
*   Matplotlib


*   Keras

Data Science Tools


*   Hadoop
*   MongoDB

*   MySQL
*   Neo4j

*   Apache Spark

Below are a few examples of evaluating arithmetic expressions in Python
"""

#This a simple arithmetic expression to mutiply then add integers
(3*4)+5

#This will convert 200 minutes to hours by dividing by 60
200/60

"""**Objectives:**


*   Some of the popular languages that Data Scientists use
*   libraries used by Data Scientists

*   Data Science Tools
*   Arithmetic operation

*   formula builing

Author:
Monika Jain
"""